# Defines the configuration version.
# The only possible value is "2".
version: "2"

linters:
  # Enable specific linter.
  # https://golangci-lint.run/usage/linters/#enabled-by-default
  enable:
    - asasalint
    - bidichk
    - bodyclose
    - copyloopvar
    - errcheck
    - funlen
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nosprintfhostport
    - reassign
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - testifylint
    - unconvert
    - unparam
    - unused
    - whitespace
  # All available settings of specific linters.
  settings:
    funlen:
      # Checks the number of lines in a function.
      # If lower than 0, disable the check.
      # Default: 60
      lines: 80
      # Checks the number of statements in a function.
      # If lower than 0, disable the check.
      # Default: 40
      statements: -1
      # Ignore comments when counting lines.
      # Default: true
      ignore-comments: true

formatters:
  # Enable specific formatter.
  # Default: [] (uses standard Go formatting)
  enable:
    - gofmt
    - goimports
    - golines
  # Formatters settings.
  settings:
    goimports:
      # A list of prefixes, which, if set, checks import paths
      # with the given prefixes are grouped after 3rd-party packages.
      # Default: []
      local-prefixes:
        - worker-sample
    golines:
      # Target maximum line length.
      # Default: 100
      max-len: 120

# Options for analysis running.
run:
  # Number of operating system threads (`GOMAXPROCS`) that can execute golangci-lint simultaneously.
  # Default: 0 (automatically set to match Linux container CPU quota and
  # fall back to the number of logical CPUs in the machine)
  concurrency: 4
