# Defines the configuration version.
# The only possible value is "2".
version: "2"

linters:
  # Enable specific linter.
  # https://golangci-lint.run/usage/linters/#enabled-by-default
  enable:
    - asasalint
    - bidichk
    - bodyclose
    - copyloopvar
    - errcheck
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nosprintfhostport
    - reassign
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - testifylint
    - unparam
    - unused

formatters:
  # Enable specific formatter.
  # Default: [] (uses standard Go formatting)
  enable:
    - gofmt
    - goimports

# Options for analysis running.
run:
  # Number of operating system threads (`GOMAXPROCS`) that can execute golangci-lint simultaneously.
  # Default: 0 (automatically set to match Linux container CPU quota and
  # fall back to the number of logical CPUs in the machine)
  concurrency: 4
